<?xml version="1.0"?>
<!--
<!DOCTYPE TRACLabsControllers SYSTEM "TRACLabsControllers.dtd">
-->

<!DOCTYPE TRACLabsControllers [ 
    <!ELEMENT TRACLabsControllers (SerialPort?,Controller+)>
    <!ELEMENT SerialPort EMPTY>
    <!ATTLIST SerialPort port CDATA #REQUIRED
                         baud CDATA "9600"
                         stopBits CDATA "1"
                         parity (noParity|evenParity|oddParity) "noParity">
    <!ELEMENT Controller (SerialPort?, Axis+)>
    <!ATTLIST Controller busAddress CDATA "0">
    <!ELEMENT Axis (Motor,Encoder,Homing,Profile?,ServoFilter?)>
    <!ATTLIST Axis axisID ( 0| 1| 2| 3| 4| 5| 6| 7| 8| 9|
	                       10|11|12|13|14|15|16|17|18|19|
	                       20|21|22|23|24|25|26|27|28|29|
						   30|31) "0">
    <!ELEMENT Motor EMPTY>
    <!ATTLIST Motor ampType  (PWMSignMag | PWM5050) "PWMSignMag"
                    hasBrake (false|true) "false"
                    motorType (brushed|brushless) "brushed"
                    poleCount NMTOKEN "3">
    <!ELEMENT Encoder EMPTY>
	<!ATTLIST Encoder countsPerMeasure NMTOKEN #REQUIRED
	                  countsPerCycle   NMTOKEN #REQUIRED>
	<!ELEMENT Homing (rangeOfMotion,Profile?,ServoFilter?)>
	<!ATTLIST Homing mode (noHoming|reverseLimit|forwardLimit|bothLimits|homeAndIndex) "bothLimits"
	                 zeroOffset NMTOKEN "0"
					 hasHardLimits (true|false) "true"
					 hasLimitSensors (true|false) "false"
					 hasHomeSensor (true|false) "false"
					 limitsMayBind (true|false) "false">
	<!ELEMENT Profile EMPTY>
	<!ATTLIST Profile units (degrees|radians|counts) "counts"
	                  pos NMTOKEN "0"
	                  vel NMTOKEN "1"
	                  acc NMTOKEN "1"
					  dec NMTOKEN "0"
	                  jerk NMTOKEN "0">
	<!ELEMENT ServoFilter EMPTY>
	<!ATTLIST ServoFilter kp NMTOKEN #REQUIRED
	                      kd NMTOKEN #REQUIRED
	                      ki NMTOKEN #REQUIRED
  	                      kvff NMTOKEN "0"
  	                      kaff NMTOKEN "0"
  	                      kout NMTOKEN "65535"
	                      il NMTOKEN #REQUIRED
  	                      ol NMTOKEN "32767"
  	                      bias NMTOKEN "0"
	                      elim NMTOKEN #REQUIRED>

	<!ELEMENT rangeOfMotion EMPTY>
	<!ATTLIST rangeOfMotion units (counts|degrees|radians|meters|inches) #REQUIRED
	                        value NMTOKEN "0">
]>

<!-- 
NOTE: profile and servo filter values are optimized for no-load conditions.
Their values will most likely need to be adjusted for a given load. 
-->
<TRACLabsControllers>
	<Controller busAddress="0">
		<SerialPort port="COM7" baud="9600" stopBits="1" parity="noParity" />
		<Axis axisID="0">
			<Motor ampType="PWMSignMag" motorType="brushed" />
			<Encoder countsPerMeasure="12000" countsPerCycle="2000" />
			<Homing>
				<rangeOfMotion units="degrees" value="350.0" />
				<Profile units="degrees" pos="350.0" vel="20.0" acc="1.0" />
				<ServoFilter kp="100" kd="50" ki="100" il="1000" ol="16384" elim="150"/>
			</Homing>
			<Profile units="degrees" pos="0.0" vel="10.0" acc="5.0" />
			<ServoFilter kp="100" kd="50" ki="100" il="1000" elim="150"/>
		</Axis>
		<Axis axisID="1">
			<Motor ampType="PWMSignMag" motorType="brushed" />
			<Encoder countsPerMeasure="12000" countsPerCycle="2000" />
			<Homing>
				<rangeOfMotion units="degrees" value="120.0" />
				<Profile units="degrees" pos="120.0" vel="10.0" acc="5.0" />
				<ServoFilter kp="150" kd="50" ki="100" il="1000" ol="16384" elim="100"/>
			</Homing>
			<Profile units="degrees" pos="0.0" vel="120.0" acc="5.0" />
			<ServoFilter kp="100" kd="50" ki="100" il="1000" elim="100"/>
		</Axis>
		<Axis axisID="2">
			<Motor ampType="PWMSignMag" motorType="brushed" />
			<Encoder countsPerMeasure="12000" countsPerCycle="2000" />
			<Homing>
				<rangeOfMotion units="degrees" value="120.0" />
				<Profile units="degrees" pos="120.0" vel="10.0" acc="5.0" />
				<ServoFilter kp="150" kd="150" ki="250" il="1000" ol="16384" elim="100"/>
			</Homing>
			<Profile units="degrees" pos="0.0" vel="10.0" acc="5.0" />
			<ServoFilter kp="150" kd="150" ki="250" il="1000" elim="100"/>
		</Axis>
		<Axis axisID="3">
			<Motor ampType="PWMSignMag" motorType="brushed" />
			<Encoder countsPerMeasure="221184" countsPerCycle="64" />
			<!--verge counts/measure =
                16 lines/motor rev * 4 encoder counts/line *
                30/10 pulley ratio * 
                32 threads/inch (an 8-32 screw) *
                1 inch screw length / 10 degrees/inch *
                360 degrees/rev -->
			<Homing zeroOffset="2300" limitsMayBind="true">
				<rangeOfMotion units="degrees" value="110.0" />
				<Profile units="degrees" pos="11.0" vel="2.0" acc="4.0" />
				<ServoFilter kp="150" kd="50" ki="100" il="1000" ol="16384" elim="200"/>
			</Homing>
			<Profile units="degrees" pos="0.0" vel="2.0" acc="4.0" />
			<ServoFilter kp="150" kd="50" ki="100" il="1000" elim="400"/>
		</Axis>
	</Controller>
</TRACLabsControllers>
